source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YRPopupPane_Example', :exclusive => true do
  pod "YRPopupPane", :path => "../"
end

target 'YRPopupPane_Tests', :exclusive => true do
  pod "YRPopupPane", :path => "../"

  
end
